language: java
jdk:
  - oraclejdk7
  - openjdk7

before_install:
  - git submodule update --init --recursive
  - sudo hostname "$(hostname | cut -c1-63)" # Fix for travis issue https://github.com/travis-ci/travis-ci/issues/5227
  - sed -e "s/^\\(127\\.0\\.0\\.1.*\\)/\\1 $(hostname | cut -c1-63)/" /etc/hosts | sudo tee /etc/hosts

script: 
  - "./test.sh"
  - "ant test"
  - "ant jar"
